---
title: "az_resdept_dtw"
author: "Lydia Bleifuss"
date: "3/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
#Helpful Packages
library(tidyverse)
library(janitor)
library(here)
library(readxl)
library(kableExtra)
library(skimr)
library(naniar)
library(VIM)
library(ggfortify)
library(lubridate)
library(tsibble)
library(dplyr)


#Spatial Clipping 
library(USAboundaries) # Download shape files
library(USAboundariesData)
library(sf) 
```

```{r}
# 1. Read both files in (csvs) 

az_dtw <- read_excel(here::here("State", "Arizona", "AZ Dept Water Resources","Raw Data", "gwis_dtw.xlsx")) %>% 
  clean_names()  %>% 
  rename(site_well_site_id = wlwa_site_well_site_id) #renaming to match the same column in az_site 

az_site <- read_excel(here::here("State", "Arizona", "AZ Dept Water Resources","Raw Data", "gwis_sites.xlsx")) %>% 
  clean_names()
```

```{r}
# 2. Join dtw and site filies

az_join <- inner_join(az_dtw, az_site, by = "site_well_site_id") %>%  #joining by site ID
  select(site_sisrc_code, site_well_site_id, wlwa_measurement_date, wlwa_depth_to_water, site_latitude_decimal, site_longit_decimal)  #selecting useful columns

#Exploring missingness
#skim(az_join)

#az_join_anti <- anti_join(az_dtw, az_site, by = "site_well_site_id") #all well dtw measurements that don't match up are in 2019 
```

```{r}
# 3. Export as csv to check locations in ArcMap 
#create a better Arc check file, removing rows that do not have lat and long 

#state_simple_datum <- az_join %>% 
  #drop_na() %>%  #if necessary
  #filter(lat_long_datum == "x") #if necessary

#skim()

#write_csv(state_simple_datum, "state_simple_export_datum.csv", append = FALSE)

#Make sure that .csv is on the end of file you are wanting to get into ArcGIS, it won't recognize them without a file type (.csv preferable) 
```


```{r}
# 4. Create dataframe for Deb to evaluate in ArcGIS
# well_id, lat, long, min_date, max_date, measurement, unique years, spearman rank under criteria:
 # > =10 measurements, >= 5 distinct years, 1 pt after 2010, 1 pt before 1980 

az_join_deb_all <- az_join %>% 
  #select(usgs_id, latitude, longitude, measurement_date_and_time, depth_to_water) %>% 
  dplyr::rename(agency_cd = site_sisrc_code, site_id = site_well_site_id, dtw = wlwa_depth_to_water, lat = site_latitude_decimal, long = site_longit_decimal, measure_date = wlwa_measurement_date) %>% #renaming to have reproducible code below
  drop_na(dtw) %>% #dropping rows that do not have a well measurement
  drop_na(lat) %>% #dropping rows that do not have spatial info 
  mutate(date = as.Date(measure_date, "%m/%d/%Y")) %>% #putting date into useable format
  mutate(year = lubridate::year(date)) %>% #extracting year to determine unique years later
  mutate(dec_date = decimal_date(date)) %>% #converting to decimal date
  #mutate(check_date = date_decimal(dec_date, tz = "UTC")) #decimal dates look correct
  group_by(site_id) %>% #by well...calculate
  mutate(date_min = min(dec_date), 
         date_max = max(dec_date),
         measurement_dist = n_distinct(dtw), #distinct well measurements by well
         year_dist = n_distinct(year)) 

az_join_deb <- az_join_deb_all %>% #creating simplified version of df to display ALL wells before criteria applied in Arc GIS
  select(agency_cd, site_id, lat, long, date_min, date_max, measurement_dist, year_dist) %>% 
  distinct(site_id, .keep_all = TRUE)

length(unique(az_join_deb$site_id)) #34419 sites before clipping

```



```{r}
#Clip to state boundaries
az_shp <- us_states(resolution = "high", states = "AZ") %>%  #read in AZ shp file
  st_transform(crs = 4269) #set CRS for NAD83

az_state_spatial <- az_join_deb %>% 
  st_as_sf(coords=c("long","lat"), #creating geometry column with lat and long to clip with az_shp 
           crs=4269) #NAD83 (EPSG:4269) 
           

az_state_clip <- st_intersection(az_shp, az_state_spatial) %>% # This filters for points inside of the az shape file
  select(site_id)


length(unique(az_state_clip$site_id)) #checking in on how many sites there are left 
#34236 (so ~200 wells were taken out of the df that were outside AZ bounds)


#CHECK in map
az_state_map <- ggplot() +
  geom_sf(data = az_state_clip,
          colour = "forestgreen", 
           size = 0.1,
           alpha = 0.5)+
  geom_sf(data = az_shp,
          fill = NA,
          colour = "black")
#az_state_map

#Create df with only wells inside the state boundary 
az_state_clean_clip <- inner_join(az_join_deb, az_state_clip, by = "site_id") %>% 
  select(!geometry) %>% 
  mutate(source = "lb_state")


length(unique(az_state_clean_clip$site_id)) #checking in on how many sites there are left 
#34236 (Great! Kept out wells outside state boarders)


```




```{r}
az_spear <- az_join_deb_all %>% #creating new df to calculate Spearman's Rank 
  group_by(site_id) %>% #by well 
  dplyr::summarise(spear_rank = cor(dec_date, dtw, 
                   method='spearman')) 

az_join_deb_spear <- inner_join(az_spear, az_join_deb_all, by = "site_id") %>% #adding in df with spear ranks and simplifying w/ criteria
    filter(measurement_dist >= 10) %>% #only kept wells with >= 10 measurments
  filter(year_dist >=5) %>% #only kept wells with >=5 distinct years
  filter(date_max >= 2010) %>% #identifying wells that have measurements at or beyond 2010
  filter(date_min <= 1980) %>% #identifying wells that have measurements at or before 1980
  distinct(site_id, .keep_all = TRUE) %>%  #only keeping unique rows (don't need all dtw measurements for the purpose of this dataset)
  select(site_id, lat, long, date_min, date_max, measurement_dist, year_dist, spear_rank) #%>% 
  #drop_na(lat) #no missing lat, long

#This is now irrelevant due to above criteria
# az_join_deb_greater_spear <- az_join_deb_spear %>% 
#   filter(year_dist >= 5) #Testing to see what it looks like with only wells that have 5+ years with one measurement or more, now only 6,309 wells 

```


```{r}
#Negative DTW Measurement Evaluation Code

az_neg_wells <- inner_join(az_spear, az_join_deb_all, by = "site_id") %>% #adding in df with spear ranks and simplifying w/ criteria
    filter(measurement_dist >= 10) %>% #only kept wells with >= 10 measurments
  filter(year_dist >=5) %>% #only kept wells with >=5 distinct years
  filter(date_max >= 2010) %>% #identifying wells that have measurements at or beyond 2010
  filter(date_min <= 1980) %>% #identifying wells that have measurements at or before 1980
  filter(dtw < 0) %>% #79 negative Measurements
  select(site_id) %>% #only keeping these well ids so I can make a df will all well measurements to evaluate neg values in context 
  distinct(site_id, .keep_all = TRUE) #only 5 wells have negative measurements

az_neg_wells_analysis <- inner_join(az_neg_wells, az_join_deb_all, by = "site_id") %>% 
  select(site_id, date, dtw, date_min, date_max)

az_split_df <- split(az_neg_wells_analysis, az_neg_wells_analysis$site_id) #Can click on each well icon in list to assess well individually and sort by date for greater eficiency 
  
#Analysis results in negative dtw tracking Google Doc sheet 

```


```{r}
# 5. Export as csv to check  in ArcMap 

write_csv(az_join_deb_spear, "az_dwr_deb_spear.csv", append = FALSE)
write_csv(az_join_deb, "az_dwr_deb.csv", append = FALSE)

```


```{r}
# 4. OLD
#Create dataframe for Deb to evaluate in ArcGIS
# well_id, lat, long, min_date, max_date, #measurement, #unique years

# az_join_deb <- az_join %>% 
#   #select(site_well_site_id, wlwa_measurement_date, wlwa_depth_to_water, site_latitude_decimal, site_longit_decimal) %>% 
#   rename(site_id = site_well_site_id, dtw = wlwa_depth_to_water, lat = site_latitude_decimal, long = site_longit_decimal, measure_date = wlwa_measurement_date) %>% #renaming to have reproducible code below
#   drop_na(dtw) %>% #dropping rows that do not have a well measurement
#   mutate(date = as.Date(measure_date, "%m/%d/%Y")) %>% #putting date into useable format
#   mutate(year = lubridate::year(date)) %>% #extracting year to determine unique years later
#   mutate(dec_date = decimal_date(date)) %>% #converting to decimal date
#   #mutate(check_date = date_decimal(dec_date, tz = "UTC")) #decimal dates look correct
#   group_by(site_id) %>% #by well...calculate
#   mutate(date_min = min(dec_date), 
#          date_max = max(dec_date),
#          measurement_dist = n_distinct(dtw), #distinct well measurements by well
#          year_dist = n_distinct(year)) %>% 
#   distinct(site_id, .keep_all = TRUE) %>% #only keeping unique rows (don't need all dtw measurements for the purpose of this dataset)
#   select(site_id, lat, long, date_min, date_max, measurement_dist, year_dist)# %>% 
#  # drop_na(lat) #no missing lat, long
# 
# 
# az_join_deb_greater <- az_join_deb %>% 
#   filter(year_dist >= 5) #Testing to see what it looks like with only wells that have 5+ years with one measurement or more, now only 9,060 wells 

```


